# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 07 Mar 2026 10:03:34 +0000
*               @ALL          1
*               @user         8
