<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 07 Mar 2026 10:03:34 +0000
 */
$conf['basedir'] = '/';
$conf['title'] = 'dokuwiki-markdown';
$conf['lang'] = 'en';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
