# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 07 Mar 2026 10:03:34 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$3ZA9oeWS1BV6fl6JdPEoVOi9lZ6RCY2PRO7YpZ.m9SXrjUh.Yyaei:admin:admin@admin.com:admin,user
